# Generated by Django 5.2.13 on 2026-04-08 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('index', models.AutoField(primary_key=True, serialize=False)),
                ('member_number', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('id_number', models.CharField(max_length=50, unique=True)),
                ('date_of_birth', models.DateField()),
                ('contact', models.CharField(max_length=100)),
                ('sex', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=20)),
                ('educational_qualification', models.CharField(max_length=150)),
            ],
        ),
    ]
