# Generated by Django 5.2.13 on 2026-04-08 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='member',
            options={'ordering': ['display_order', 'index']},
        ),
        migrations.AddField(
            model_name='member',
            name='display_order',
            field=models.IntegerField(default=0),
        ),
    ]
